### ISSUE TITLE
Migrate this repo to the vshaxe organization?

### ISSUE THREAD

**Issue by Gama11** [jcward/vscode-hxcpp-debug#35]
https://github.com/vshaxe

I think it would be nice to have all the relevant repos in one central place, including this one.

@nadako @Simn @ibilon

**Comment by ibilon** [comment]
If @jcward is ok with this I think it'll be nice too.

**Comment by Gama11** [comment]
Ping @jcward.

**Comment by nadako** [comment]
Someone is volunteering to support this? Maybe @waneck?

**Comment by jcward** [comment]
@Gama11 This code is open source and MIT licensed. You can use it pursuant to the terms of the [license](https://github.com/jcward/vscode-hxcpp-debug/blob/master/LICENSE).

**Comment by Gama11** [comment]
@jcward Fair enough - so you're suggesting a fork?

Personally, I'd prefer to avoid that - seems much better to pool our efforts. :)

Not to mention that users would likely be quite confused if there are two hxcpp-debuggers for VSCode in different places.

**Comment by jcward** [comment]
What were you suggesting?

**Comment by Gama11** [comment]
Like I mentioned in the issue title, I think it would make sense to transfer this repo to the vshaxe organization, so it seems a bit more "official"? From there on, we could try to include the debug adapter out of the box in vshaxe releases - could still be a separate repo via a submodule or something.

I think that would improve the user experience quite a bit - only one extension to install for users. :)

**Comment by jcward** [comment]
So let me see if I understand this correctly: you want to host (maybe own) the code I wrote because it'd provide the best experience for your users and your repo?

Hmm. I must admit, so far, I'm failing to see the allure of this proposition.

**Comment by Gama11** [comment]
A simple "no" would've sufficed. ;) And I don't want to "own" anything, I'm mostly trying to improve the user experience for Flixel users, which is one of the big reasons I'm contributing to vshaxe.

Anyway, thanks anyway for the work on this plugin, works quite well already from what I could tell - first time I ever got hxcpp debugging to work.

**Comment by jcward** [comment]
I'm just trying to help you understand the idea from my perspective.

**Comment by waneck** [comment]
I don't understand why you're taking offense on this, @jcward . It's not about ownership - you would still be the owner of the repository, and you will still make the decisions there. There are no "our" users vs "your" users. There are Haxe users and it's about integrating the debugger with the language server extensions, and provide a centralized place to find them. From my view point as a user, getting the debugger to work at first was quite confusing. Also, there are some missing integrations between both repositories which would benefit both projects.

**Comment by jcward** [comment]
@waneck, can I pick projects from your account to migrate to mine?

I see no mention of commit rights or decision making. I asked for clarification.

I'm not trying to be rude, I simply see no benefit, no consideration for me whatsoever. So... feel free to fork it, that's the license.

**Comment by thomasuster** [comment]
Yea why not do a fork? That seems like that makes a ton of sense.

**Comment by hughsando** [comment]
Jeff - the hxcpp repo started off as "mine".  But it really did make more
sense to transfer it to the haxefoundation group, where I still have full
rights over it.  But also the haxefoundation guys have access - for example
Andy Li set up the automated testing without me having to do anything.
Of course, this might detract from your plans for this repo, but I really
think you can view the transfer to a more visible/official group as a
win-win.

Hugh

**Comment by nadako** [comment]
I don't really get how this turned into conflict here. What's the actual problem? Is it because of the initial haxe-languageserver and vshaxe experiment I did? Because I was under the impression that we [figured it out](https://github.com/vshaxe/vshaxe/issues/11).

There's a lot of people working on VS Code support for Haxe now, we created an umbrella organization for all vscode-related projects and when creating this issue, I think @Gama11 assumed that @jcward would like to join it and move his repositories to it and work together further, since hxcpp debugger is really a cruicial part. But clearly there's some misunderstanding and grudge, but I fail to see the reason.

Anyway, for the greater good and further development of the actual tool, I guess forking is indeed a good option.

**Comment by andyli** [comment]
> pick projects from your account to migrate to mine

vshaxe is an organization, not a personal account. Think of it this way - @Gama11 want to invite you to join the team and collaborate. The vshaxe "organization" works just like a group of projects.

Personally, I've no opinion on whether vscode-hxcpp-debug should be transferred or not. I just want to point out that it is not a rude/unusual thing to ask. I believe it is even nicer then just forking without ask.

If Jeff's concern is about the credit, I think the vshaxe team member would be fine to put a h1 header in the readme to state Jeff is the owner/author/maintainer.

**Comment by jcward** [comment]
I shall simply restate: I see no mention of commit rights, no invitation to join any group, no mention of the future decision making process.

The truth is, I don't care about those things, but it would have been proper and respectable to offer them.

The lesson is, if you're going to ask to subsume someone's repo, you should present them with a gracious and respectful offer.

**Comment by tanis2000** [comment]
@hughsando what you and @jcward (and everyone else) are saying is exactly the same. It's just the way it's been proposed that lacks manners. Whoever is in charge of that organization should have made a proposal to @jcward mentioning all the things that he's just written up there. It's much better to be asked to join an organization and to discuss that kind of stuff before asking to migrate code to a new home with no details. 

But that's how communication breaks down over the net... sometimes it just sounds rude.

BTW I'm in favor of having all the code under the same umbrella, as long as contributors retain their rights and you guys don't make yet another project stall just because then there's no one managing the project and merging PRs like it happened with my contributions to haxe-debugger and other repos.

**Comment by Simn** [comment]
> and you guys don't make yet another project stall just because then there's no one managing the project and merging PRs like it happened with my contributions to haxe-debugger and other repos.

What's that about? I'm not seeing any PRs from you on hxcpp-debugger, merged or otherwise. We also had multiple Haxe Foundation members, including me, involved in figuring out a very tricky problem (#25)  which was ultimately fixed. I think I spent two hours on IRC helping you with this issue, so this criticism comes out of nowhere for me. Really curious what projects you think we're stalling.

**Comment by tanis2000** [comment]
@Simn sorry I meant `hxcpp-debugger` but wrote `haxe-debugger`. But you do know about it and figured it out yourself.

Now, I don't get why you feel you're being criticized as you've actually been extremely helpful in solving that issue. 

My critic is directed at the PR linked to that issue.
It's been made at the end of January and reviewed at the end of April. That's 3 months.. quite some time IMHO since there is an organization behind it and not just one person. 

I've already talked about that to @ncannasse so that's nothing new to the HaxeFoundation.

**Comment by Simn** [comment]
I'm confused, https://github.com/HaxeFoundation/hxcpp-debugger/pull/10 says it was opened on April 28th and received a first comment on the same day.

**Comment by tanis2000** [comment]
@Simn I'm confused as well.. I must be mistaking the issue then. Anyway if that's the case it was opened on April 28th, reviewed the same day, fixed the day after and left there until May 19th. That's about 20 days.. much better than 3 months indeed, but still...

My bitterness comes from trying to actually use Haxe professionally and hitting walls here and there. I know that OSS isn't guaranteed to work, but the overall feeling with Haxe is that general response time is very slow even if I fix and improve stuff on my own instead of waiting for someone over at HaxeFoundation to do it for me. 

Again, this is MY perception and I'm not pointing fingers at persons. You shouldn't take this personally. If I'm the only one seeing this, then let it be :)

**Comment by jcward** [comment]
Seems like this topic has been discussed enough. Locking to avoid excess notifications to the participants. Feel free to open a new issue or message me with further comments.
